name: Argentina 2016
favicon: null
layout_spectrum: 0.4848268018104136
typography_spectrum: 0.38038201816380024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.22419765684753656
  lightness: 0.38355264253914356
  saturation: 0.37662716675549746
  rhythmicContrast: 0.517815024824813
purpose: []
